### ISSUE TITLE
[Proposal] Should EOD be optional?

### ISSUE THREAD

**Issue by marler8997** [TinyVG/specification#2]
What do you think about making EOD optional?

**Comment by ikskuh** [comment]
No, the EOD marker isn't there "just because it's nice", but it's required to determine if a file is actually valid TinyVG or just random garbage.

It also allows you to read TinyVG files from a stream with additional data after it *without* encoding (or knowing) the encoded file size before streaming the data.

**Comment by marler8997** [comment]
In the stream example I agree you would need EOD. Why would you say EOD is required to know whether the file is valid, doesn't the magic/version/header serve that purpose well enough?
