### ISSUE TITLE
[Proposal] Add color names

### ISSUE THREAD

**Issue by robert-ancell** [TinyVG/specification#36]
A renderer might want to use one TVG file to render multiple similar images that differ by an accent color. To allow this I propose adding optional names to the color table. Suggested format:

Header:
```
...
color_count VarUInt
color_name_count VarUInt
```

Color Name:
```
color_index VarUInt
name_length VarUInt
name [name_length]u8
```

- Names may only use the characters a-zA-Z_.
- A color may have multiple names
- If a name is used multiple times only the first entry is considered valid.

**Comment by robert-ancell** [comment]
Alternatives considered:
- Just use the indexes instead of names - this is likely to break if a file changes color order or doesn't support this feature.
- Have a list of names that match the order of the colors - doesn't allow multiple names

**Comment by ikskuh** [comment]
I don't think this is a feature that suits TinyVG well, as it already is an application specific thing, and you can then also just use a well-defined index instead of a name, making the tooling such that it preserves well-defined indices.
Remind yourself that you could also just implement a custom color encoding and use names instead of RGBA values directly
